apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: new-service
  description: Spring boot service.
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: MOE
